import { yekan } from '@/utils/font'
import './globals.css'
import Layout from '@/layout/Layout'

import NextProvider from '@/providers/nextAuth'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'> 
      <body className={yekan.className}>
        <NextProvider>
        <Layout>
          <div className='min-h-[500px]'>
        {children}
          </div>
        </Layout>
        </NextProvider>
      </body>
    </html>
  )
}
